### PR TITLE
ESM migration

### PR DESCRIPTION
**Pull request by CarlosGamero**

### CODE REVIEW

**Review by kibertoad — APPROVED** [review]
Thank you so much, Carlos!

**Comment by tomaszhanc** [comment]
@CarlosGamero @kibertoad Could you give more context about what this change does? For a newbie, it's just adding the `.js` extension for imports. Why is it better that way?

**Comment by CarlosGamero** [comment]
Hey @tomaszhanc, first of all, thanks for asking 🙌! let me try to provide a bit of context.

We were using CommonJS, the "old" way to write modules and the only supported method on Node.js some time ago, ESM is the newer and standardised way of writing modules on JS/TS ecosystem.

We have decided to migrate all our services because it lets us keep in step with where the broader Node.js ecosystem is going, also, we can benefit from better integration with our tooling, and have better compatibility across the board. 

As you mentioned, the biggest difference in our daily work is the `.js` imports, but IDE should handle it automatically and we also have linter rules checking that.
There are some other changes in syntax and differences, I recommend searching CommonJS vs ESM in Google as most likely someone has a nice article explaining them much better than I can do, [here](https://www.hoeser.dev/blog/2023-02-21-cjs-vs-esm/) is a nice one that can work as a start point.

I hope this message helps you and if you have questions please feel free to reach out on Slack 🙏

**Comment by tomaszhanc** [comment]
@CarlosGamero I'm new to the JS/TS ecosystem, so thank you for your patience and detailed explanation. I will read more in the link you added here. Thanks!

**Pull request merged**
